<a href="https://colab.research.google.com/github/Diwakar-Gupta/Data-Science-APRIL/blob/main/22-04-16-Numpy/Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

In [8]:
l = np.array([1,2,5,6,7])
print(l)

[1 2 5 6 7]


*  size
*  dtype
*  shape
*  ndim

In [12]:
print('Type', type(l))
print('Size', l.size)
print('dtype', l.dtype)

Type <class 'numpy.ndarray'>
Size 5
dtype int64


Dtypes: https://numpy.org/devdocs/user/basics.types.html



*   int
*   uint
*   float {8, 16, 32, 64}


Numpy array is Homogeneous.


In [64]:
# l = np.array([1,2,5,6,70000], dtype='int8')
l = np.array([1,2,5,6.9,70000])

print(l.dtype)
print(l)

float64
[1.0e+00 2.0e+00 5.0e+00 6.9e+00 7.0e+04]


e+x => 10^x

In [24]:
l = np.array([1,2,5,6.6,9], dtype='int32')

print(l.dtype)
print(l)

int32
[1 2 5 6 9]


## Performance

**Memory**

In [26]:
import sys

a = 9
print('Bits', sys.getsizeof(a)*8)

Bits 224


In [39]:
a = np.array([3,5,8,5])

print(a.dtype)
print('Storage of 1 data in Bit\'s', a.itemsize*8)
print('Storage of complete array in bit\'s', a.nbytes*8)

int64
Storage of 1 data in Bit's 64
Storage of complete array in bit's 256


**Time**

In [33]:
ar = np.arange(2, 10002)
print(ar.size)

10000


In [41]:
s = 0
for i in ar:
    s = s+i
print(s)

50015000


In [34]:
def sumArray(l):
    sum = 0
    for i in l:
        sum = sum+i
    return sum

%timeit sumArray(ar) # python function

1000 loops, best of 5: 1.11 ms per loop


In [35]:
%timeit ar.sum() # numpy function

The slowest run took 20.57 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 8.75 µs per loop


# Numpy array from Scratch



*   `np.zeros(size)`
*   `np.ones(size)`
*   `np.full(size, value)` # repeats 7 10 times
*   `np.arange(start, stop, step)`


In [45]:
ar = np.zeros(10, dtype=np.int32)
print(ar)
print(ar.dtype)
print(ar.size)

[0 0 0 0 0 0 0 0 0 0]
int32
10


In [46]:
ar = np.ones(10, dtype=np.int32)
print(ar)
print(ar.dtype)
print(ar.size)

[1 1 1 1 1 1 1 1 1 1]
int32
10


In [48]:
ar = np.full(10, 7, dtype=np.int32) # repeats
print(ar)
print(ar.dtype)
print(ar.size)

[7 7 7 7 7 7 7 7 7 7]
int32
10


In [53]:
print(list(range(20, 9, -2)))
ar = np.arange(20, 9, -2)
print(ar)

[20, 18, 16, 14, 12, 10]
[20 18 16 14 12 10]


# Slicing / Indexing

*  Same as python list

In [62]:
ar = np.arange(2, 10)
print(ar)
print(ar.size)

[2 3 4 5 6 7 8 9]
8


In [63]:
print(ar[0])
print(ar[-2])

2
8


In [61]:
ar[: : -1]

array([9, 8, 7, 6, 5, 4, 3, 2])

Task



1.   https://www.hackerrank.com/challenges/np-arrays/problem?isFullScreen=true
2.   https://www.hackerrank.com/challenges/np-zeros-and-ones/problem?isFullScreen=true



```
def arrays(arr):
    l=arr[::-1];
    l=numpy.array(l,float)
    return l
```

```
import numpy

s = input()
l = s.split(' ') # ['3', '3', ...... '3]

for i in range(len(l)):
    l[i] = int(l[i])

print(numpy.zeros( l, dtype='int8' ))
print(numpy.ones( l, dtype='int8' ))
```

In [78]:
# without using full function +
ar = np.ones(12)*8
print(ar)
print(ar.size)
print(ar.dtype)

[8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
12
float64


# Multi Dimension

multi dim = Array inside another array



*   ndim
*   shape : length of all array one inside other



In [83]:
ar = np.array([1,2,3,4])
print(type(ar))
print(ar.ndim)
print(ar.shape)

<class 'numpy.ndarray'>
1
(4,)


In [86]:
ar = np.array([ [1, 2], [3,4], [4,5], [6,7] ])

print(ar)
print(ar.ndim)
print(ar.shape)
print(ar[0])
print(ar[1])

[[1 2]
 [3 4]
 [4 5]
 [6 7]]
2
(4, 2)
[1 2]
[3 4]


In [97]:
ar = np.array([ [[1, 1, 1], [2,1 ,1 ]], [[3,1 ,1 ],[4,1 ,1 ]], [[4,1 ,1 ],[5,1 ,1 ]], [[6,1 ,1 ],[7,1 ,1 ]] ])

print(ar.ndim)
print(ar.shape)
print(ar.size) # count of values{int, float}
print(len(ar), len(ar[0]), len(ar[0][0]))

3
(4, 2, 3)
24
4 2 3


In [90]:
print(ar)

[[[1 1 1]
  [2 1 1]]

 [[3 1 1]
  [4 1 1]]

 [[4 1 1]
  [5 1 1]]

 [[6 1 1]
  [7 1 1]]]


In [95]:
print(ar[0][1][0])
print(ar[0, 1, 0])

2
2


## from Scratch

*  `np.ones( (2,5,3) )`
*  `np.zeros( (2,5,3) )`
*  `np.arange(12).reshape(3, -1)`
*  full

In [102]:
ar = np.ones( (2,5,3) )

print(ar)
print(ar.ndim)
print(ar.shape)
print(ar.size)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
3
(2, 5, 3)
30


In [108]:
a = ar.reshape(3, 5, 2)

print(a)
print(a.ndim)
print(a.shape)
print(a.size)

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]
3
(3, 5, 2)
30


In [112]:
a = ar.reshape(3, -1)

# print(a)
print(a.ndim)
print(a.shape)
print(a.size)

2
(3, 10)
30


In [113]:
ar = np.arange(12)

print(ar)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [120]:
ar.reshape(-1, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

## Indexing / Slicing

In [127]:
ar = np.arange(12).reshape(3, -1)

print(ar.shape)
print(ar)

(3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [130]:
print(ar[1])

ar[1, 2]

[4 5 6 7]


6

In [131]:
print(ar)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [140]:
print(ar[0:2])
print()
print(ar[0:2, 1:])
print()
print(ar[0:2, :0:-1])

[[0 1 2 3]
 [4 5 6 7]]

[[1 2 3]
 [5 6 7]]

[[3 2 1]
 [7 6 5]]
