<a href="https://colab.research.google.com/github/Diwakar-Gupta/Data-Science-APRIL/blob/main/22-07-28/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Install**
1. https://pytorch.org/get-started/locally/

**Tutorials**
1.  https://pytorch.org/tutorials/beginner/basics/quickstart_tutorial.html

2.  https://www.learnpytorch.io/

**Links**
1. https://paperswithcode.com/trends

In [ ]:
! pip3 install torch torchvision torchaudio

In [1]:
import torch
import numpy as np

In [2]:
np.array([1,2,34])

array([ 1,  2, 34])

In [3]:
a = torch.tensor([1,2,3,4])

In [4]:
a.size()

torch.Size([4])

In [5]:
b = torch.tensor([
              [1,2,3],
              [4,5,6]
])
b.shape, b.size()

(torch.Size([2, 3]), torch.Size([2, 3]))

In [6]:
b.size()

torch.Size([2, 3])

In [8]:
sliced_tensor = b[:, 1:3].clone()
sliced_tensor

tensor([[2, 3],
        [5, 6]])

In [9]:
torch.ones(2,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [10]:
torch.zeros(4)

tensor([0., 0., 0., 0.])

In [11]:
a = torch.ones(2,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [12]:
a.numpy()

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

# CPU GPU

In [13]:
a = torch.tensor([4,5,6,7], device='cpu')
a

tensor([4, 5, 6, 7])

In [14]:
a+1

tensor([5, 6, 7, 8])

In [15]:
a = torch.tensor([4,5,6,7], device='cuda')
a

tensor([4, 5, 6, 7], device='cuda:0')

In [16]:
a+3

tensor([ 7,  8,  9, 10], device='cuda:0')

In [17]:
a_cpu = torch.tensor([5,6,7,8])
a_cpu

tensor([5, 6, 7, 8])

In [18]:
a_gpu = a_cpu.to('cuda')
a_gpu

tensor([5, 6, 7, 8], device='cuda:0')

In [19]:
a_cpu

tensor([5, 6, 7, 8])

In [20]:
if torch.cuda.is_available():
    device = 'cuda'
else:
    device = 'cpu'

device

'cuda'

In [21]:
a_cpu.to(device)

tensor([5, 6, 7, 8], device='cuda:0')

# Save load

In [23]:
torch.save(a_cpu, 'a_tensor.t')

In [24]:
torch.load('a_tensor.t')

tensor([5, 6, 7, 8])

#Network

In [50]:
import torch
import torch.nn.functional as F

class network(torch.nn.Module):

    def __init__(self):
        super(network, self).__init__()

        # https://pytorch.org/docs/stable/generated/torch.nn.Conv2d.html
        self.conv1 = torch.nn.Conv2d(1, 6, 3)
        self.conv2 = torch.nn.Conv2d(6, 18, 3)

        self.fc1 = torch.nn.Linear(18 * 6 * 6, 120)
        self.fc2 = torch.nn.Linear(120, 84)
        self.fc3 = torch.nn.Linear(84, 10)
    
    def forward(self, x):
        x = self.conv1(x)
        x = F.relu(x)
        x = F.max_pool2d( x, (2,2) )

        x = self.conv2(x)
        x = F.relu(x)
        x = F.max_pool2d( x, (2,2) )

        x = x.view(-1, self.num_flat_features(x)) # Flatten layer
        
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = F.relu(self.fc3(x))

        return x
    
    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features

In [51]:
a = torch.ones(2,3)
a.view(1, 6)

tensor([[1., 1., 1., 1., 1., 1.]])

In [52]:
net = network()

In [53]:
print(net)

network(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 18, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=648, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [54]:
params = list(net.parameters())
print(len(params))

10


In [55]:
inp = torch.randn(1, 1, 32, 32)
out = net(inp)

In [56]:
out

tensor([[0.1144, 0.0438, 0.0438, 0.0000, 0.0000, 0.0892, 0.0000, 0.0000, 0.0000,
         0.0807]], grad_fn=<ReluBackward0>)

In [57]:
out.shape

torch.Size([1, 10])

#Training

In [58]:
output = net(inp)
target = torch.randn(10)
target = target.view(1, -1)

criterion = torch.nn.MSELoss()

loss = criterion(target, output)
print(loss)

tensor(0.5504, grad_fn=<MseLossBackward0>)


https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html

In [59]:
loss.backward() # calculate gradients

optim = torch.optim.SGD(net.parameters(), lr=1e-2, momentum=0.9)

optim.step() # gradient descent