<a href="https://colab.research.google.com/github/Diwakar-Gupta/Data-Science-APRIL/blob/main/22-08-14-NLP/Spam_Ham_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
messages=pd.read_csv('https://raw.githubusercontent.com/Pepcoders/Data-Science-January/main/NLP/sms',sep='\t',names=['label','message'])

In [ ]:
messages

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [ ]:
#Data Cleaning and Processing
import nltk
import re
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer


In [ ]:
ps=PorterStemmer()
corpus=[]

In [ ]:
for i in range(0,len(messages)):
  review = re.sub('[^a-zA-Z]', ' ', messages['message'][i])
  review=review.lower()
  review=review.split()

  review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
  review=" ".join(review)
  corpus.append(review)



In [ ]:
## Create Bag Of Words Model
## Convert words to numeric form

from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=3000)
X=cv.fit_transform(corpus).toarray()

In [ ]:
messages['label']

0        ham
1        ham
2       spam
3        ham
4        ham
        ... 
5567    spam
5568     ham
5569     ham
5570     ham
5571     ham
Name: label, Length: 5572, dtype: object

In [ ]:
from sklearn.preprocessing import LabelEncoder

lb=LabelEncoder()
y=lb.fit_transform(messages['label'])

In [ ]:
y

array([0, 0, 1, ..., 0, 0, 0])

In [ ]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
## Model Building

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.naive_bayes import MultinomialNB,GaussianNB

spam_detect_model_1=MultinomialNB()

spam_detect_model_2=GaussianNB()


In [ ]:
spam_detect_model_1.fit(X_train,y_train)

MultinomialNB()

In [ ]:
spam_detect_model_2.fit(X_train,y_train)

GaussianNB()

In [ ]:
spam_detect_model_1.score(X_train,y_train)

0.989230424052053

In [ ]:
spam_detect_model_2.score(X_train,y_train)

0.8873681848777204

In [ ]:
spam_detect_model_1.score(X_test,y_test)

0.9838565022421525

In [ ]:
spam_detect_model_2.score(X_test,y_test)

0.8600896860986547

In [ ]:
###############CONCLUSION##################
#### MULTINOMIAL NB IS PERFORMING WELL ####

In [ ]:
X_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
set(spam_detect_model_1.predict(X_test))

{0, 1}